# Generated by Django 3.2.4 on 2021-06-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='book_cover',
        ),
    ]
