# Generated by Django 3.2.4 on 2021-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_remove_booklist_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='book_cover',
            field=models.ImageField(default=-1.0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
